services:
  dev:
    container_name: dev
    platform: linux/x86_64
    build: ./dev
    environment:
      - SECRET_KEY_SANDBOX=${SECRET_KEY_SANDBOX}
      - TERMINAL_CODE_SANDBOX=${TERMINAL_CODE_SANDBOX}
      - SECRET_KEY_PRODUCTION=${SECRET_KEY_PRODUCTION}
      - TERMINAL_CODE_PRODUCTION=${TERMINAL_CODE_PRODUCTION}
      - PAYMENT_RETURN=${PAYMENT_RETURN}
      - HOST_VNPAY=${HOST_VNPAY}
      - ENV=${ENV}
    command: uvicorn main:app --reload --host 0.0.0.0 --port ${HOST_VNPAY}
    ports:
      - "${HOST_VNPAY}:${HOST_VNPAY}"
    volumes:
      - ./dev:/app


# volumes:
#   mysql_data:

# networks:
#   backend:
#     driver: bridge